const baseURL = "https://api.heroku.com/apps/";

const decoder = new TextDecoder();

const createUrl = (endpoint, herokuApp) => `${baseURL}${herokuApp}${endpoint}`;

/**
 * Create a request to the Heroku api with the supplied arguments.
 * This function applies headers that must be present for all the requests
 * @param {string} endpoint The request endpoint, e.g. /dynos
 * @param {string} herokuApp The Heroku app used
 * @param {string} apiToken The Heroku API token, must have access to the specified Heroku app
 * @param {string} method The HTTP method used, e.g. "POST", "GET" or "PATCH"
 * @param {any} body JSON data to be sent
 * @returns {Promise<Response>} A promise with the response
 */
const makeHerokuRequest = (
    endpoint,
    herokuApp,
    apiToken,
    method = "GET",
    body = undefined
) => {
    return fetch(createUrl(endpoint, herokuApp), {
        method,
        headers: {
            Authorization: `Bearer ${apiToken}`,
            "Content-Type": "application/json",
            Accept: "application/vnd.heroku+json; version=3",
        },
        body: JSON.stringify(body),
    });
};

/**
 * Set the error message to display to the user.
 * @param {string} message The error message, defaults to ""
 */
const setError = (message = "") => {
    const error = document.getElementById("error");
    error.textContent = message;
};

/**
 * Set the logging result to display to the user
 * @param {string} message The logging string, default to ""
 */
const setLog = (message = "") => {
    const log = document.getElementById("output");
    log.textContent = message;
};

/**
 * Read the stream and update the output visible to the user
 * @param {ReadableStreamReader<Uint8Array>} reader
 */
const readStream = (reader) => {
    const log = document.getElementById("output");
    reader.read().then(({ done, value }) => {
        if (done) {
            console.log("Stream complete");
            return;
        }
        setLog(log.textContent + decoder.decode(value));

        return readStream(reader);
    });
};

/**
 * Get the log stream from heroku
 * @param {string} dyno  The name of the created dyno
 * @param {string} herokuApp  The name of the Heroku app
 * @param {string} apiToken  The API token used to authenticate
 */
const getLogStream = (dyno, herokuApp, apiToken) => {
    makeHerokuRequest("/log-sessions", herokuApp, apiToken, "POST", {
        dyno,
        tail: true,
    }).then(async (res) => {
        const content = await res.json();
        if (res.ok) {
            fetch(content.logplex_url)
                .then((response) => response.body.getReader())
                .then(readStream);
        } else {
            setError(content.message);
        }
    });
};

/**
 * Start the Dyno and get the log stream generated by the dyno.
 */
const startDyno = () => {
    setError();
    setLog();

    const herokuApp = document.getElementById("herokuApp").value;
    const herokuApiKey = document.getElementById("herokuApiKey").value;
    const name = document.getElementById("name").value;

    makeHerokuRequest("/dynos", herokuApp, herokuApiKey, "POST", {
        command: "serverless",
        env: {
            NAME: name,
        },
    }).then(async (res) => {
        const content = await res.json();
        if (res.ok) {
            getLogStream(content.name, herokuApp, herokuApiKey);
        } else {
            setError(content.message);
        }
    });
};
