const baseURL = "https://api.heroku.com/apps/";

const decoder = new TextDecoder();

const createUrl = (endpoint, herokuApp) => `${baseURL}${herokuApp}${endpoint}`;

/**
 * Create request to Heroku API with supplied arguments
 * This function applies headers that must be present for all the requests
 * @param {string} endpoint  Request endpoint, e.g. /dynos
 * @param {string} herokuApp  Heroku app used
 * @param {string} apiToken  Heroku API token, must have access to specified Heroku app
 * @param {string} method  HTTP method used, e.g. "POST", "GET" or "PATCH"
 * @param {any} body  JSON data to be sent
 * @returns {Promise<Response>}  Promise with response
 */
const makeHerokuRequest = (endpoint, herokuApp, apiToken, method = "GET", body = undefined) => {
    return fetch(createUrl(endpoint, herokuApp), {
        method,
        headers: {
            Authorization: `Bearer ${apiToken}`,
            "Content-Type": "application/json",
            Accept: "application/vnd.heroku+json; version=3",
        },
        body: JSON.stringify(body),
    });
};

/**
 * Set error message to display to user
 * @param {string} message  Error message, defaults to ""
 */
const setError = (message = "") => {
    const error = document.getElementById("error");
    error.textContent = message;
};

/**
 * Set logging result to display to user
 * @param {string} message  Logging string, default to ""
 */
const setLog = (message = "") => {
    const log = document.getElementById("output");
    log.textContent = message;
};

/**
 * Read stream and update output visible to user
 * @param {ReadableStreamReader<Uint8Array>} reader
 */
const readStream = (reader) => {
    const log = document.getElementById("output");
    reader.read().then(({ done, value }) => {
        if (done) {
            console.log("Stream complete");
            return;
        }
        setLog(log.textContent + decoder.decode(value));

        return readStream(reader);
    });
};

/**
 * Get log stream from heroku
 * @param {string} dyno  Name of created dyno
 * @param {string} herokuApp  Name of Heroku app
 * @param {string} apiToken  API token used to authenticate
 */
const getLogStream = (dyno, herokuApp, apiToken) => {
    return makeHerokuRequest("/log-sessions", herokuApp, apiToken, "POST", {
        dyno,
        source: "app",
        tail: true,
    }).then(async (res) => {
        const content = await res.json();
        if (res.ok) {
            fetch(content.logplex_url)
                .then((response) => response.body.getReader())
                .then(readStream);
        } else {
            throw new Error(content.message);
        }
    });
};

/**
 * Creates a simple loader element, animated by CSS
 */
const createLoader = () => {
    const loaderNode = document.getElementById("loader");
    const ldsRing = document.createElement("div");
    ldsRing.setAttribute("id", "lds-ring");
    for (let i = 0; i < 4; i++) {
        ldsRing.appendChild(document.createElement("div"));
    }
    loaderNode.appendChild(ldsRing);
};

const removeLoader = () => {
    document.getElementById("lds-ring").remove();
};

/**
 * Start dyno and get log stream generated by dyno
 */
const startDyno = () => {
    setError();
    setLog();

    document.getElementById("startButton").setAttribute("disabled", true);
    createLoader();
    const herokuAppNode = document.getElementById("herokuApp");
    const herokuApiKeyNode = document.getElementById("herokuApiKey");
    const commandNode = document.getElementById("command");

    const environmentVariablesNode = Array.from(document.getElementsByClassName("environmentVariable"));
    try {
        if (!herokuAppNode.value || !herokuApiKeyNode.value || !commandNode.value) {
            throw new Error("Please fill out the form");
        }

        const environmentVariables = environmentVariablesNode.reduce((prev, curr) => {
            const keyNode = curr.getElementsByClassName("environmentVariableKey").item(0);
            const valueNode = curr.getElementsByClassName("environmentVariableValue").item(0);
            if (!keyNode.value && !valueNode.value) {
                throw new Error("Please fill out environment variables values");
            }
            return { ...prev, [keyNode.value]: valueNode.value };
        }, {});

        const herokuApp = herokuAppNode.value;
        const herokuApiKey = herokuApiKeyNode.value;
        const command = commandNode.value;

        makeHerokuRequest("/dynos", herokuApp, herokuApiKey, "POST", {
            command,
            env: environmentVariables,
        })
            .then(async (res) => {
                const content = await res.json();
                if (res.ok) {
                    return getLogStream(content.name, herokuApp, herokuApiKey);
                } else {
                    throw new Error(content.message);
                }
            })
            .finally(() => {
                document.getElementById("startButton").removeAttribute("disabled");
                removeLoader();
            });
    } catch (error) {
        setError(error.message);
        document.getElementById("startButton").removeAttribute("disabled");
        removeLoader();
    }
};
